accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/<int:user_pk>/',views.profile,name='profile'),
    path('profile/<int:user_pk>/follow/', views.follow, name='follow'),
]

books/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "books"
urlpatterns = [
    path("category/", views.category_list),
    path("", views.book_list),
    path("<int:book_pk>/", views.book_detail),
    path("threads/", views.thread_list),
    path("threads/<int:thread_pk>/", views.thread_detail),
    path("<int:book_pk>/threads/", views.create_thread),
    path("threads/<int:thread_pk>/comments/", views.create_comment),
    path("comments/<int:comment_pk>/", views.comment_detail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("", views.index, name="index"),
# path("create/", views.create, name="create"),
# path("<int:pk>/", views.detail, name="detail"),
# path("<int:pk>/update/", views.update, name="update"),
# path("<int:pk>/delete/", views.delete, name="delete"),

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include("books.urls")),
    path('accounts/', include("accounts.urls")),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # 관심 장르
    interested_genres = models.ManyToManyField(
        'books.Category',
        related_name='interested_users',
        blank=True,
        verbose_name='관심 장르'
    )

    # 성별: 선택지 제공 (M/F)
    GENDER_CHOICES = [
        ('M', '남성'),
        ('F', '여성'),
    ]
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True,
        null=True,
        verbose_name='성별',
    )

    # 나이 (빈 값 허용)
    age = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='나이',
    )

    # 주간 평균 독서 시간
    weekly_avg_reading_time = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='주간 평균 독서 시간',
    )

    # 연간 독서량
    annual_reading_amount = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='연간 독서량',
    )

    # 프로필 사진
    profile_img = models.ImageField(
        upload_to='profile_images/',
        blank=True,
        null=True,
        verbose_name='프로필 사진',
    )

    # 팔로우
    followings = models.ManyToManyField(
        'self',
        symmetrical=False,
        related_name='followers',
        blank=True,
        verbose_name='팔로우',
    )

    # def get_favorite_categories_display(self):
    #     return self.favorite_categories.split(',') if self.favorite_categories else []

    def __str__(self):
        return self.username
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from books.models import Category

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    # 관심 장르: Category에서 가져옴
    interested_genres = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="관심 장르"
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'last_name',
            'first_name',
            'email',
            'gender',
            'age',
            'weekly_avg_reading_time',
            'annual_reading_amount',
            'profile_img',
            'interested_genres',
        )
        labels = {
            'username': '아이디',
            'last_name': '성',
            'first_name': '이름',
            'email': '이메일',
            'gender': '성별',
            'age': '나이',
            'weekly_avg_reading_time': '주간 평균 독서 시간',
            'annual_reading_amount': '연간 독서량',
            'profile_img': '프로필 사진',
            'interested_genres': '관심 장르',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = "비밀번호"
        self.fields['password2'].label = "비밀번호 확인"

def save(self, commit=True):
    user = super().save(commit=False)
    if commit:
        user.save()
        self.save_m2m()  # ← 여기가 정답!
    return user

    

class CustomUserChangeForm(UserChangeForm):
    # 관심 장르 필드 (체크박스 + 복수 선택)
    interested_genres = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="관심 장르"
    )

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            'username',
            'last_name',
            'first_name',
            'email',
            'gender',
            'age',
            'weekly_avg_reading_time',
            'annual_reading_amount',
            'profile_img',
            'interested_genres',
        )
        labels = {
            'username': '아이디',
            'last_name': '성',
            'first_name': '이름',
            'email': '이메일',
            'gender': '성별',
            'age': '나이',
            'weekly_avg_reading_time': '주간 평균 독서 시간',
            'annual_reading_amount': '연간 독서량',
            'profile_img': '프로필 사진',
            'interested_genres': '관심 장르',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password')  # 비밀번호 필드 제거
        self.fields['interested_genres'].queryset = Category.objects.all() 


    def save(self, commit=True):
        user = super().save(commit=False)
        # genres = self.cleaned_data.get('interested_genres')
        # if genres:
        #     user.favorite_categories = ','.join([g.name for g in genres])
        # else:
        #     user.favorite_categories = ''
        if commit:
            user.save()
            self.save_m2m()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import get_user_model, update_session_auth_hash
from books.models import Thread

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('books:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
@require_POST
def logout(request):
    auth_logout(request)
    return redirect('books:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('books:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'user': request.user,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_POST
def delete(request):
    request.user.delete()
    return redirect('books:index')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('books:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

@login_required
@require_http_methods(['GET'])
def profile(request,user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    threads = person.thread_set.all()
    context = {
        'person':person,
        'threads':threads,
    }
    return render(request,'accounts/profile.html',context)

@login_required
@require_http_methods(['POST'])
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', user_pk=person.pk)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>회원정보 수정</h1>

<form action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-success" value="Submit">
</form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>

<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="로그인">
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{person.username}}님의 프로필</h1>
<hr>
<p>{% if user.profile_img %}
    <img src="{{ user.profile_img.url }}" alt="프로필 사진">
  {% else %}
    <img src="{% static 'default_profile.png' %}" alt="기본 프로필">
  {% endif %}
</p>
<!-- 회원 정보 -->
<p>아이디: {{ person.username }}</p>
<p>이메일: {{ person.email }}</p>
<p>이름: {{ person.last_name }}{{ person.first_name }}</p>
<p>성별: {{ person.gender }}</p>
<p>나이: {{ person.age }}</p>
<p>주간 평균 독서 시간: {{ person.weekly_avg_reading_time }}시간</p>
<p>연간 독서량: {{ person.annual_reading_amount }}권</p>
<p>팔로워 : {{ person.followers.count }}</p>
<p>팔로잉 : {{ person.followings.count }}</p>
<hr>

<p>
    {% if request.user == person %}
    <a href="{% url "accounts:update" %}">회원정보 수정</a>
    <form action="{% url 'accounts:delete' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <input type="submit" class="btn btn-secondary" value="회원탈퇴">
    </form>
    
    {% else %}
    <form action="{% url 'accounts:follow' person.pk %}" method="post">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
        <input type="submit" class="btn btn-secondary" value="언팔로우">
        {% else %}
        <input type="submit" class="btn btn-success" value="팔로우">
        {% endif %}
    </form>
    {% endif %}
</p>
<hr>
<h3>{{ person.username }}님의 쓰레드 목록</h3>
<ul>
  {% for thread in threads %}
    <li>
      <a href="{% url "books:thread_detail" thread.pk%}">title</a> - 좋아요: {{ thread.like_users|length }}
    </li>
  {% empty %}
    <p>작성한 쓰레드가 없습니다.</p>
  {% endfor %}
</ul>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>회원가입</h1>
<form action="{% url "accounts:signup" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="회원가입">
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>회원정보 수정</h1>
<form action="{% url "accounts:update" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    
    <p>
        <strong>비밀번호 변경:</strong>
        <a href="{% url 'change_password' user.pk %}">비밀번호 변경하기</a>
    </p>
    
    <input type="submit" class="btn btn-success" value="Submit">
</form>

{% endblock content %}