accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/<int:user_pk>/',views.profile,name='profile'),
    path('profile/<int:user_pk>/follow/', views.follow, name='follow'),
]

books/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "books"
urlpatterns = [
    path("category/", views.category_list),
    path("", views.book_list),
    path("<int:book_pk>/", views.book_detail),
    path("threads/", views.thread_list),
    path("threads/<int:thread_pk>/", views.thread_detail),
    path("<int:book_pk>/threads/", views.create_thread),
    path("threads/<int:thread_pk>/comments/", views.create_comment),
    path("comments/<int:comment_pk>/", views.comment_detail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("", views.index, name="index"),
# path("create/", views.create, name="create"),
# path("<int:pk>/", views.detail, name="detail"),
# path("<int:pk>/update/", views.update, name="update"),
# path("<int:pk>/delete/", views.delete, name="delete"),

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include("books.urls")),
    path('accounts/', include("accounts.urls")),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">  
  <link href="https://fonts.googleapis.com/css2?family=Pretendard&display=swap" rel="stylesheet">
  <title>Document</title>
  <style>
    * {
      font-family: 'Pretendard', sans-serif;
    }
    input, textarea, select, button {
      font-family: inherit;
    }
    .book-card img {
      height: 500px;
      object-fit: cover;
    }
    .book-card .card-title {
      font-size: 1rem;
      font-weight: 600;
    }
    .book-card .card-text {
      font-size: 0.9rem;
      color: #666;
    }
    .book-card .card-subtitle {
      font-size: 0.8rem;
      color: #999;
    }
    .book-card .card-body {
      display: flex;
      flex-direction: column;
    }
    .book-card .card-subtitle {
      margin-top: auto;
    }
  </style>
</head>

<body>
  <nav class="navbar bg-success navbar-expand-lg border-bottom border-body mb-4" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'books:index' %}">ThRead</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto text-end mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'books:index' %}">INDEX</a>
          </li>

          {% comment %} 로그인 한 경우 {% endcomment %}
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books:create' %}">CREATE</a>
            </li>
            <li class="nav-item">
              {% comment %} <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' request.user.username %}">MY PROFILE</a> {% endcomment %}
              <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' request.user.pk %}">MY PROFILE</a>
            </li>
            <li class="nav-item">
              <form action="{% url "accounts:logout" %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="nav-link" value="LOGOUT">
              </form>
            </li>

          {% comment %} 로그인 하지 않은 경우 {% endcomment %}
          {% else %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">SIGNUP</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>