accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/<int:user_pk>/',views.profile,name='profile'),
    path('profile/<int:user_pk>/follow/', views.follow, name='follow'),
]

books/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "books"
urlpatterns = [
    path("category/", views.category_list),
    path("", views.book_list),
    path("<int:book_pk>/", views.book_detail),
    path("threads/", views.thread_list),
    path("threads/<int:thread_pk>/", views.thread_detail),
    path("<int:book_pk>/threads/", views.create_thread),
    path("threads/<int:thread_pk>/comments/", views.create_comment),
    path("comments/<int:comment_pk>/", views.comment_detail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("", views.index, name="index"),
# path("create/", views.create, name="create"),
# path("<int:pk>/", views.detail, name="detail"),
# path("<int:pk>/update/", views.update, name="update"),
# path("<int:pk>/delete/", views.delete, name="delete"),

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include("books.urls")),
    path('accounts/', include("accounts.urls")),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    CATEGORY_CHOICES = [
        ('LITERATURE', '소설/시/희곡'),
        ('ECONOMY', '경제/경영'),
        ('DEVELOPMENT', '자기계발'),
        ('HUMANITY', '인문/교양'),
        ('SCIENCE', '과학'),
        ('HOBBY', '취미/실용'),
        ('MINORS', '어린이/청소년'),
    ]

    name = models.CharField(
        max_length=100,
        unique=True,
        choices=CATEGORY_CHOICES,
        help_text = '도서 종류를 선택해주세요.',
        verbose_name='카테고리',
        )

    def __str__(self):
        return self.get_name_display()
    

class Book(models.Model):
    # user = models.ForeignKey(
    #     settings.AUTH_USER_MODEL,
    #     related_name='books',
    #     verbose_name='등록한 사용자',
    #     on_delete=models.CASCADE,
    # )
    title = models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    isbn = models.TextField()
    description = models.TextField()
    cover = models.ImageField(upload_to='book_covers/', blank=True)
    publisher = models.TextField()
    pub_date = models.TextField()
    author = models.TextField()
    customer_review_rank = models.IntegerField()


    # author_info = models.TextField(blank=True)
    # author_works = models.CharField(max_length=50, blank=True)
    
    # audio_file = models.FileField(upload_to="tts/", blank=True, null=True)
    
    
# 특정 도서에 대한 게시글
class Thread(models.Model):
    # user = models.ForeignKey(
    #     settings.AUTH_USER_MODEL,
    #     on_delete=models.CASCADE,
    #     verbose_name='작성자',
    # )
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='해당 도서', related_name='threads')
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    reading_date = models.DateField(verbose_name='독서일')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # cover_img = models.ImageField(upload_to="thread_covers/", blank=True, null=True)
    # like_users = models.ManyToManyField(
    #     settings.AUTH_USER_MODEL,
    #     related_name='liked_threads',
    #     blank=True,
    #     verbose_name='좋아요한 사용자'
    # )

    def __str__(self):
        return self.title
    
    
class Comment(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, verbose_name="스레드 댓글", related_name="comments")
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

books/forms.py
from django import forms
from .models import Book, Thread


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = [
            "user",
            "author_info",
            "author_profile_img",
            "author_works",
            "audio_file",
        ]

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ('title', 'content', 'reading_date',)
        widgets = {
            'reading_date': forms.DateInput(
                attrs={'type': 'date', 'class': 'form-control'}
            ),
        }

books/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from django.db.models import Count
from .models import Category, Book, Thread, Comment
from .serializers import CategorylistSerializer,BooklistSerializer,BookSerializer
from .forms import BookForm,ThreadForm
from .utils import (
    process_wikipedia_info,
    generate_author_gpt_info,
    generate_audio_script,
    create_tts_audio,
    create_ai_image,
)
from .serializers import ThreadListSerializer, ThreadSerializer, CommentSerializer

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


@api_view(['GET'])
def category_list(request):
    categories = Category.objects.all()
    serializer = CategorylistSerializer(categories,many=True)
    return Response(serializer.data)

@api_view(['GET'])
def book_list(request):
    books = Book.objects.all()
    serializer = BooklistSerializer(books,many=True)
    return Response(serializer.data)

@api_view(['GET'])
def book_detail(request,book_pk):
    books = Book.objects.annotate(num_of_threads=Count('threads')).get(pk=book_pk)
    serializer = BookSerializer(books)
    return Response(serializer.data)


@api_view(['GET'])
def thread_list(request):
    threads = Thread.objects.all()
    serializer = ThreadListSerializer(threads, many=True)
    return Response(serializer.data)


@api_view(['POST'])
def create_thread(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    serializer = ThreadSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save(book=book)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET', 'PUT', 'DELETE'])
def thread_detail(request, thread_pk):
    thread = Thread.objects.annotate(num_of_comments=Count('comments')).get(pk=thread_pk)
    if request.method == 'GET':
        serializer = ThreadSerializer(thread)
        return Response(serializer.data)
    
    elif request.method == 'PUT':
        serializer = ThreadSerializer(thread, data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)

    elif request.method == 'DELETE':
        thread.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['POST'])
def create_comment(request, thread_pk):
    thread = Thread.objects.get(pk=thread_pk)
    serializer = CommentSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save(thread=thread)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET', 'PUT', 'DELETE'])
def comment_detail(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'GET':
        serializer = CommentSerializer(comment)
        return Response(serializer.data)
    
    elif request.method == 'PUT':
        serializer = CommentSerializer(comment, data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)
    
    elif request.method == 'DELETE':
        comment.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
# @login_required
# def create(request):
#     if request.method == "POST":
#         form = BookForm(request.POST, request.FILES)
#         if form.is_valid():
#             book = form.save(commit=False)
#             book.user =request.user
#             wiki_summary = process_wikipedia_info(book)

#             author_info, author_works = generate_author_gpt_info(
#                 book, wiki_summary
#             )
#             book.author_info = author_info
#             book.author_works = author_works
#             book.save()

#             audio_script = generate_audio_script(book, wiki_summary)

#             audio_file_path = create_tts_audio(book, audio_script)
#             if audio_file_path:
#                 book.audio_file = audio_file_path
#                 book.save()

#             return redirect("books:detail", book.pk)
#     else:
#         form = BookForm()
#     context = {"form": form}
#     return render(request, "books/create.html", context)

# # @login_required
# def detail(request, pk):
#     book = Book.objects.get(pk=pk)
#     threadform = ThreadForm()
#     threads = book.thread_set.all()
#     context = {
#         "book": book,
#         "threads": threads,
#         'threadform': threadform,
#     }
#     return render(request, "books/detail.html", context)

# @login_required
# def update(request, pk):
#     book = Book.objects.get(pk=pk)
#     if request.method == "POST":
#         form = BookForm(request.POST, request.FILES, instance=book)
#         if form.is_valid():
#             form.save()
#             return redirect("books:detail", pk)
#     else:
#         form = BookForm(instance=book)
#     context = {
#         "form": form,
#         "book": book,
#     }
#     return render(request, "books/update.html", context)

# @login_required
# def delete(request, pk):
#     book = Book.objects.get(pk=pk)
#     if request.user == book.user:
#         book.delete()
#         return redirect("books:index")

books/templates/books/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>도서 등록 페이지</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>도서 상세 페이지</h1>
  <hr>

  {% if book.cover_image %}
    <div style="width: 300px;">
      <img src="{{ book.cover_image.url }}" alt="" class="w-100">
    </div>
  {% endif %}

  <h2 class="mt-2">{{ book.title }}</h2>
  <h5>{{book.get_category_display}}</h5>
  <p>{{ book.description }}</p>
  <h5>회원 리뷰 평점 : {{ book.customer_review_rank }} / 10</h5>

  <hr>

  <div style="display: flex; justify-content: center; align-items: center; gap: 2rem; margin-bottom: 2rem;">
    
    {% if book.author_profile_img %}
      <div style="width: 120px; height: 120px;">
        <img 
          src="{{ book.author_profile_img.url }}" 
          alt="{{ book.author }}" 
          style="width: 100%; height: 100%; object-fit: cover; border-radius: 50%;"
        >
      </div>
    {% endif %}
    
    <div style="flex: 1;">
      <h3>{{ book.author }}</h3>
      <p><strong>대표작:</strong> {{ book.author_works }}</p>
      <p>{{ book.author_info }}</p>
      <small style="color: #888;">
        ※ 작가 대표작과 작가 정보는 AI가 생성한 답변으로, 정확하지 않을 수 있습니다.
      </small>
    </div>
  </div>

  <hr>

  {% if book.audio_file %}
    <h5>도서 정보 음성 듣기:</h5>
    <audio controls>
      <source src="{{ book.audio_file.url }}" type="audio/mpeg">
    </audio>
  {% else %}
    <p>음성 파일이 없습니다.</p>
  {% endif %}

  <hr>
  {% if request.user == book.user %}
  <a href="{% url 'books:update' book.pk %}" class="btn btn-secondary">UPDATE</a>
  <form action="{% url 'books:delete' book.pk %}" method="POST" class="d-inline">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-danger">
  </form>

  <hr>
  {% endif %}
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="m-0">Thread</h1>
    <a href="{% url "books:thread_create" book.pk %}">쓰레드 작성</a>
  </div>
  {% for thread in threads %}
  <li>
    <a href="{% url "books:thread_detail" thread.pk %}">
      {{thread.title}}
    </a>
  </li>
  {% endfor %}
  <hr>

  <div>
    <a href="{% url 'books:index' %}" class="btn btn-secondary">BACK</a>
  </div>
{% endblock content %}

books/templates/books/index.html
{% extends 'base.html' %} {% block content %}
<h1>메인 페이지</h1>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
  {% for book in books %}
  <div class="col">
    <div class="card book-card h-100">
      {% if book.cover_image %}
      <img src="{{ book.cover_image.url }}" class="card-img-top" alt="..." />
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
        <p class="card-text">{{ book.description }}</p>
        <h6 class="card-subtitle mb-2">
          <a href="{% url 'books:detail' book.pk %}" class="btn btn-success">Detail</a>
        </h6>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

books/templates/books/thread_create.html
{% extends "base.html" %}

{% block content %}
  <h1>쓰레드 작성 페이지</h1>
  <form action="{% url "books:thread_create" pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-success mb-2" value="전송"><br>
    <a href="{% url "books:detail" pk %}" class="btn btn-outline-danger">취소</a>
  </form>
{% endblock content %}

books/templates/books/thread_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ thread.title }}</h1>
    <img src="{{thread.cover_img}}" alt="이미지 로딩 실패" width="550">
    <div class="d-flex align-items-center gap-4 mb-3">
      <div>
        
        <strong>도서:</strong>
        <a href="{% url 'books:detail' thread.book.pk %}" class="ms-1">
          {{ thread.book.title }}
        </a>
      </div>
    
      <div>
        <strong>작성자:</strong>
        <a href="{% url 'accounts:profile' thread.user.pk %}" class="ms-1">
          {{ thread.user.username }}
        </a>
      </div>
    
      <div>
        <strong>독서일:</strong>
        <span class="ms-1">{{ thread.reading_date }}</span>
      </div>
    </div>
    
    <hr>

    <p>{{ thread.content }}</p>
    <p>좋아요 수 : {{thread.like_users.all|length}}    </p>
    <form action="{% url "books:thread_likes" thread.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in thread.like_users.all %}
     <input type="submit" class="btn btn-secondary" value="좋아요 취소">
    {% else %}
    <input type="submit" class="btn btn-secondary" value="좋아요">
     {% endif %}  
  </form>
    
    {% if request.user == thread.user %}
    <hr>

    <a href="{% url "books:thread_update" thread.pk %}" class="btn btn-success mb-2">수정</a>

    <form action="{% url "books:thread_delete" thread.pk %}" method="POST">
        {% csrf_token %}
       <input type="submit" class="btn btn-secondary" value="삭제">  
    </form>
        
    {% endif %}

{% endblock content %}

books/templates/books/thread_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>쓰레드 수정 페이지</h1>
  <form action="{% url "books:thread_update" thread.pk%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-success" vlaue="수정">
    <a href="{% url "books:detail" thread.book.pk %}" class="btn btn-outline-secondary">취소</a>
  </form>
{% endblock content %}

books/templates/books/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>도서 수정 페이지</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="제출">
  </form>
{% endblock content %}